### ISSUE TITLE
"Please set DEVKITPRO in your environment" error when DEVKITPRO is set.

### ISSUE THREAD

**Issue by MineRobber9000** [Lectem/3ds-cmake#9]
I have "DEVKITPRO" set to "<my home directory>/Code/3dsdev/devkitPro" and "DEVKITARM" set to "$DEVKITPRO/devkitArm". I set it as such:

````
set DEVKITPRO="$HOME/Code/3dsdev/devkitPro"
set DEVKITARM="$DEVKITPRO/devkitArm"
````

However, I still get the "Please set DEVKITPRO in your environment" error.

**Comment by Lectem** [comment]
Could you replace here https://github.com/Lectem/3ds-cmake/blob/master/DevkitArm3DS.cmake#L16 the mesage

    "Please set DEVKITPRO in your environment"

by 

    "DEVKITPRO=${DEVKITPRO} | env(DEVKITPRO)=$ENV{DEVKITPRO}"

And tell me the results ?

**Comment by MineRobber9000** [comment]
The weird thing is, I tried it again and it worked flawlessly. Not quite sure what happened, but it works now.
